const configs = {
    defaultTitle: "溪游库",
    defaultICP: "蜀ICP备18021274号-2",
    defaultLogo: "/logo.svg",
    defaultFavicon: "/favicon.ico",
    publicKey: "-----BEGIN PUBLIC KEY-----\n" +
        "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDD1jENRClo1hdOjCZAaq8FGxVP\n" +
        "W5owB/XaYvMSF3g9qntPQimol0QPKhv844IfjdsseyPcqrn9p4cbgGo2jtPtOfQ+\n" +
        "PrINf17SoVWYSKxebLdZq2v5TeiWqXRoYLyZhLfnWo3ZO4bPhP0U9WoXQR6Ek/7t\n" +
        "vvE/9qLTkQzDNGF56QIDAQAB\n" +
        "-----END PUBLIC KEY-----",
    fullpageLicenseKey: 'B2024500-5DBF4886-84798F7B-C8C76066',
    proxyBackendHost: "/go",
    vaptchaJsUrl: "://v.vaptcha.com/v3.js",
    settingUrl: "/setting",
    authUrl: "/admin/auth",
    loginUrl: "/admin/login",
    logoutUrl: "/admin/logout",
    carouselUrl: "/carousel",
    carouselListUrl: "/carousel/list",
    getCarouselUrl: "/carousel/view",
    createCarouselUrl: "/carousel/create",
    updateCarouselUrl: "/carousel/update",
    deleteCarouselUrl: "/carousel/delete",
    previewCarouselUrl: "/carousel/preview",
    updateCarouselCaptionStyleUrl: "/carousel/update-caption-style",
    setCarouselSwitchTypeUrl: "/carousel/set-switch-type",
    sortCarouselOrderUrl: "/carousel/sort-order",
    fileListUrl: "/file",
    fileInfoUrl: "/file/detail",
    updateFileUrl: "/file/update",
    uploadFileUrl: "/file/upload",
    deleteFileUrl: "/file/delete",
    postUrl: "/post",
    postListUrl: "/post/list",
    savePostUrl: "/post/save",
    getPostInfoUrl: "/post/info",
    getPostDetailUrl: "/post/detail",
    togglePostStatusUrl: "/post/toggle-status",
    deletePostUrl: "/post/delete",
    carouselSettingsUrl: "/setting/carousel",
    connectsUrl: "/setting/connects",
    loginSettingUrl: "/setting/login",
    siteSettingsUrl: "/setting/site",
    baiduSettingsUrl: "/setting/baidu",
    alipaySettingsUrl: "/setting/alipay",
    facebookSettingUrl: "/setting/facebook",
    githubSettingUrl: "/setting/github",
    giteeSettingUrl: "/setting/gitee",
    googleSettingUrl: "/setting/google",
    lineSettingUrl: "/setting/line",
    qqSettingUrl: "/setting/qq",
    twitterSettingUrl: "/setting/twitter",
    wechatSettingUrl: "/setting/wechat",
    weiboSettingUrl: "/setting/weibo",
    adminProfileUrl: "/admin/profile",
    adminConnectsUrl: "/admin/connects",
    adminCallbackUrl: "/admin/callback",
    unbindConnectUrl: "/admin/unbind",
    adminAuthorizeUrl: "/admin/authorize",
    authorizeUrl: "/admin/url",
    authorizeCallback: "/admin/callback",
    loginDuration: 3 * 24 * 60 * 60,
    imageTypes: [
        'png',
        'jpg'
    ],
    videoTypes: [
        'mp4',
        'mkv'
    ],
    uploadChunkSize: 10 * 1024 * 1024,//单位kb
    carouselEffects: {
        parallax: '失真',
        slide: '推入',
        separate: '切换',
        split: '下落',
        fade: '淡入淡出',
        blinds: '百叶窗',
        clamp: '擦除',
        wipe: '覆盖',
        cube: '方块',
        swap: '交换',
    },
    defaultTitleStyle: {
        top: 10,
        left: 10,
        font_family: '',
        font_size: '4',
        font_color: '#F8F8F8',
        font_align: 'left',
        font_shadow: '0px 0px 8px var(--main-color-transparent)',
        font_spacing: '-1px'
    },
    defaultDescriptionStyle: {
        top: 12,
        left: 10,
        font_family: '',
        font_size: '2',
        font_color: '#F8F8F8',
        font_align: 'left',
        font_shadow: '0px 0px 0.2rem var(--main-color-transparent)',
        font_spacing: '-1px'
    }
}
export default configs;
